# Introduction

This in an inspiration of one of the biggest challenge that I faced when I started in this PhD. Which is what is forest structure? There are quite a lot of arguments and various concepts of what "forest structure" should be and how should it be measured. However is that true? So in this book I will try my best to basically summarize the existing concepts and how people are recently categorized and measure the different metrices and descriptions of complexity index around the globe. This is just be a list of everything tho. How its going to be applied in different industries are still yet being decided tho. Hope everyone enjoys. 

## Scale dependency of Forests canopies 

Each **bookdown** chapter is an .Rmd file, and each .Rmd file can contain one (and only one) chapter. A chapter *must* start with a first-level heading: `# A good chapter`, and can contain one (and only one) first-level heading.

Use second-level and higher headings within chapters like: `## A short section` or `### An even shorter section`.

The `index.Rmd` file is required, and is also your first book chapter. It will be the homepage when you render the book.

## Render book

You can render the HTML version of this example book without changing anything:

1. Find the **Build** pane in the RStudio IDE, and

1. Click on **Build Book**, then select your output format, or select "All formats" if you'd like to use multiple formats from the same book source files.

Or build the book from the R console:

This book documents the methods and workflow used in my PhD project bah bah bah 
