# Application of each metrics
## Overview {-}
I think I will be basically worn out after finishing the 5 chapters up front. Thinking about the application of it its going to be tiring but whatever. I think itself can be written into a review paper tho (to be honest). and yeah after caterotization it can be categorized into so so so much. My thoughts right now is like below:

## Environments of Forests
### microclimates
#### carbon {-}
#### water {-}
### biogeochemical
## Dynamics of Forests
### regeneration (growth)
### disturbances
#### fires {-}
#### pests...etc {-}
## Biodiversity
### habitat etc birs and animals? Who knows

## Equations

Here is an equation.

\begin{equation} 
  f\left(k\right) = \binom{n}{k} p^k\left(1-p\right)^{n-k}
  (\#eq:binom)
\end{equation} 

You may refer to using `\@ref(eq:binom)`, like see Equation \@ref(eq:binom).


## Theorems and proofs

Labeled theorems can be referenced in text using `\@ref(thm:tri)`, for example, check out this smart theorem \@ref(thm:tri).

::: {.theorem #tri}
For a right triangle, if $c$ denotes the *length* of the hypotenuse
and $a$ and $b$ denote the lengths of the **other** two sides, we have
$$a^2 + b^2 = c^2$$
:::

Read more here <https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html>.

## Callout blocks


The R Markdown Cookbook provides more help on how to use custom blocks to design your own callouts: https://bookdown.org/yihui/rmarkdown-cookbook/custom-blocks.html
